```{r 02-remove-all, include = FALSE}
rm(list = ls())
```


## Vectors and columns

```{r include = FALSE}
# Setup 02-dir.R
```
```{r 02-setup-02-dir-r}
library(tidyverse)
library(here)
```


```{r include = FALSE}
# Show all files, see also fs::dir_ls()
```
```{r 02-show-all-files-see-also-fs-dir-ls}
files <- dir(here("data/weather"), full.names = TRUE)
files
```


```{r include = FALSE}
# Convert to tibble
```
```{r 02-convert-to-tibble}
files_df <-
  files %>%
  enframe()

files_df
```


```{r include = FALSE}
# Remove the name column
```
```{r 02-remove-the-name-column}
files_df_1 <-
  files %>%
  enframe(name = NULL)

files_df_1
```


```{r include = FALSE}
# Construct tibble from a vector
```
```{r 02-construct-tibble-from-a-vector}
tibble(filename = files)
```


```{r include = FALSE}
# Extract a column as a vector
```
```{r 02-extract-a-column-as-a-vector}
files_df %>%
  pull()
```


```{r include = FALSE}
# Extract a specific column as a vector
```
```{r 02-extract-a-specific-column-as-a-vector}
files_df %>%
  pull(name)
```
