```{r 03-remove-all, include = FALSE}
rm(list = ls())
```


## Named vectors and two-column tibbles

<details><summary>Setup code</summary>
```{r include = FALSE}
### Named vectors and two-column tibbles

```
```{r 03-setup-03-names-r}
library(tidyverse)
library(here)
```
</details>


```{r include = FALSE}
# Load dictionary from file
```
```{r 03-load-dictionary-from-file}
dict <- readxl::read_excel(here("data/cities.xlsx"))
dict
```


```{r include = FALSE}
# Acquire file names
```
```{r 03-acquire-file-names}
dict %>%
  pull(weather_filename)
```


```{r include = FALSE}
# Use here() to create absolute paths
```
```{r 03-use-here-to-create-absolute-paths}
dict %>%
  pull(weather_filename) %>%
  here()
```


```{r include = FALSE}
# Acquire file names as a named vector
```
```{r 03-acquire-file-names-as-a-named-vector}
dict %>%
  select(city_code, weather_filename) %>%
  deframe()
```


```{r include = FALSE}
# Not all operations maintain vector names!
```
```{r 03-not-all-operations-maintain-vector-names}
dict %>%
  select(city_code, weather_filename) %>%
  deframe() %>%
  here()
```


```{r include = FALSE}
# Move the here() call into "tibble-land"
```
```{r 03-move-the-here-call-into-tibble-land}
dict %>%
  mutate(weather_filename_here = here(weather_filename)) %>%
  select(city_code, weather_filename_here) %>%
  deframe()
```
