```{r 05-remove-all, include = FALSE}
rm(list = ls())
```


## Construction

<details><summary>Click here to make setup code visible</summary>
```{r include = FALSE}
### Construction

```
```{r 05-setup-05-construct-r}
c(1, 2, 3)
c(1:3, 5)
c(1:3, "5")
```
</details>


```{r include = FALSE}
# Use list() to construct a list, all elements can have different types and lengths:
```
```{r 05-use-list-to-construct-a-list-all-elements-can-have-different-types-and-lengths}
list(1, 2, 3)
list(1:3, 5)
list(1:3, "5")
```


```{r include = FALSE}
# Lists can be nested:
```
```{r 05-lists-can-be-nested}
list(
  1:3,
  list(4, "5"),
  list(
    list(letters[6:8]),
    9
  )
)
```


```{r include = FALSE}
# Vectors and lists can have names:
```
```{r 05-vectors-and-lists-can-have-names}
c(a = 1, b = 2, c = 3)
list(a = 1:3, b = 5)
```


```{r include = FALSE}
# Preview: vctrs::list_of() to construct typed lists
```
```{r 05-preview-vctrs-list-of-to-construct-typed-lists}
#vctrs::list_of(1, 2, 3)
#vctrs::list_of(letters[1:3], "e")
```
