```{r 05-remove-all, include = FALSE}
rm(list = ls())
```


## Manipulating all datasets

```{r include = FALSE}
### Manipulating all datasets

```
```{r 05-setup-05-map-manip-r}
library(tidyverse)
library(here)
```


```{r include = FALSE}
# Load dictionary from file
```
```{r 05-load-dictionary-from-file}
dict <- readxl::read_excel(here("data/cities.xlsx"))
dict
```


```{r include = FALSE}
# Collect input data
```
```{r 05-collect-input-data}
input_data <-
  dict %>%
  select(city_code, weather_filename) %>%
  deframe() %>%
  map(~ readxl::read_excel(here(.)))
```


```{r include = FALSE}
# Manipulate results
```
```{r 05-manipulate-results}
input_data %>%
  map(~ select(., time, contains("emperature")))
```


```{r include = FALSE}
# Manipulate results more
```
```{r 05-manipulate-results-more}
input_data %>%
  map(~ select(., time, contains("emperature"))) %>%
  map(~ filter(., temperature >= 14))
```


```{r include = FALSE}
# Create a function to manipulate
```
```{r 05-create-a-function-to-manipulate}
manipulator <- function(data) {
  data %>%
    select(time, contains("emperature")) %>%
    filter(temperature >= 14)
}
```


```{r include = FALSE}
# Functions are first-class objects!
```
```{r 05-functions-are-first-class-objects}
manipulator
```


```{r include = FALSE}
# Test the function
```
```{r 05-test-the-function}
manipulator(input_data[[4]])
```


```{r include = FALSE}
# Run the function on the entire dataset
```
```{r 05-run-the-function-on-the-entire-dataset}
manipulated_data <- map(input_data, ~ manipulator(.))
manipulated_data
```


```{r include = FALSE}
# Shortcut
```
```{r 05-shortcut}
map(input_data, manipulator)
```


```{r include = FALSE}
# Write back results: new file names
```
```{r 05-write-back-results-new-file-names}
output_filenames <- tempfile(names(input_data), fileext = ".csv")
```


```{r include = FALSE}
# Iterate over pairs
```
```{r 05-iterate-over-pairs}
map2(manipulated_data, output_filenames, ~ readr::write_csv(..1, ..2))
```


```{r include = FALSE}
# We don't really need the output
```
```{r 05-we-don-t-really-need-the-output}
walk2(manipulated_data, output_filenames, ~ readr::write_csv(..1, ..2))
```
