```{r 06-remove-all, include = FALSE}
rm(list = ls())
```


## Manipulating pairwise

<!-- Setup 06-map2.R -->
```{r 06-setup-06-map-2-r}
library(tidyverse)
library(here)
```


<!-- Load dictionary from file -->
```{r 06-load-dictionary-from-file}
dict <- readxl::read_excel(here("data/cities.xlsx"))
dict
```


<!-- Create a function to manipulate -->
```{r 06-create-a-function-to-manipulate}
manipulator <- function(data) {
  data %>%
    select(time, contains("emperature")) %>%
    filter(temperature >= 14)
}
```


<!-- Collect and manipulate input data -->
```{r 06-collect-and-manipulate-input-data}
manipulated_data <-
  dict %>%
  select(city_code, weather_filename) %>%
  deframe() %>%
  map(~ readxl::read_excel(here(.))) %>%
  map(manipulator)
```


<!-- Write back results: new file names -->
```{r 06-write-back-results-new-file-names}
output_filenames <- tempfile(names(manipulated_data), fileext = ".csv")
output_filenames
```


<!-- Iterate over pairs -->
```{r 06-iterate-over-pairs}
map2(manipulated_data, output_filenames, ~ readr::write_csv(..1, ..2))
```


<!-- We don't really need the output -->
```{r 06-we-don-t-really-need-the-output}
walk2(manipulated_data, output_filenames, ~ readr::write_csv(..1, ..2))
```
