```{r 06-remove-all, include = FALSE}
rm(list = ls())
```


## Manipulating all datasets

<details><summary>Setup code</summary>
```{r include = FALSE}
### Manipulating all datasets

```
```{r 06-setup-05-map-manip-r}
library(tidyverse)
library(here)

dict <- readxl::read_excel(here("data/cities.xlsx"))

input_data <-
  dict %>%
  select(city_code, weather_filename) %>%
  deframe() %>%
  map(~ readxl::read_excel(here(.)))
```
</details>


```{r include = FALSE}
# Manipulate results
```
```{r 06-manipulate-results}
input_data %>%
  map(~ select(., time, contains("emperature")))
```


```{r include = FALSE}
# Manipulate results more
```
```{r 06-manipulate-results-more}
input_data %>%
  map(~ select(., time, contains("emperature"))) %>%
  map(~ filter(., temperature >= 14))
```


```{r include = FALSE}
# Create a function to manipulate
```
```{r 06-create-a-function-to-manipulate}
manipulator <- function(data) {
  data %>%
    select(time, contains("emperature")) %>%
    filter(temperature >= 14)
}
```


```{r include = FALSE}
# Functions are first-class objects!
```
```{r 06-functions-are-first-class-objects}
manipulator
```


```{r include = FALSE}
# Test the function
```
```{r 06-test-the-function}
manipulator(input_data[[4]])
```


```{r include = FALSE}
# Run the function on the entire dataset
```
```{r 06-run-the-function-on-the-entire-dataset}
manipulated_data <- map(input_data, ~ manipulator(.))
manipulated_data
```


```{r include = FALSE}
# Shortcut
```
```{r 06-shortcut}
map(input_data, manipulator)
```
