```{r 10-remove-all, include = FALSE}
rm(list = ls())
```


## <No caption defined>

```{r include = FALSE}
### <No caption defined>

```
```{r 10-setup-10-mutate-map-r}
library(tidyverse)
library(here)
```


```{r include = FALSE}
# Load dictionary from file
```
```{r 10-load-dictionary-from-file}
dict <- readxl::read_excel(here("data/cities.xlsx"))
dict
```


```{r include = FALSE}
# map() on a vector
```
```{r 10-map-on-a-vector}
input_data <-
  dict %>%
  select(city_code, weather_filename) %>%
  deframe() %>%
  map(~ readxl::read_excel(here(.)))

input_data
```


```{r include = FALSE}
# Lists are also vectors, enframe() returns a nested tibble!
```
```{r 10-lists-are-also-vectors-enframe-returns-a-nested-tibble}
input_data %>%
  enframe()
```


```{r include = FALSE}
# Operate in "tibble-land": columns are vectors
```
```{r 10-operate-in-tibble-land-columns-are-vectors}
dict %>%
  select(city_code, weather_filename) %>%
  mutate(
    data = map(weather_filename, ~ readxl::read_excel(here(.)))
  )
```


```{r include = FALSE}
# Keep auxiliary columns
```
```{r 10-keep-auxiliary-columns}
dict %>%
  mutate(
    data = map(weather_filename, ~ readxl::read_excel(here(.)))
  ) %>%
  select(city_code, name, data)
```
