```{r 12-remove-all, include = FALSE}
rm(list = ls())
```


## Moving to tibble-land

<details><summary>Setup code</summary>
```{r include = FALSE}
### Moving to tibble-land

```
```{r 12-setup-12-mutate-map-r}
library(tidyverse)
library(here)

dict <- readxl::read_excel(here("data/cities.xlsx"))

input_data <-
  dict %>%
  select(city_code, weather_filename) %>%
  deframe() %>%
  map(~ readxl::read_excel(here(.)))
```
</details>


```{r include = FALSE}
# Lists are also vectors, enframe() returns a nested tibble!
```
```{r 12-lists-are-also-vectors-enframe-returns-a-nested-tibble}
input_data %>%
  enframe()
```


```{r include = FALSE}
# Operate in "tibble-land" right away: columns are vectors
```
```{r 12-operate-in-tibble-land-right-away-columns-are-vectors}
dict %>%
  select(city_code, weather_filename) %>%
  mutate(
    data = map(weather_filename, ~ readxl::read_excel(here(.)))
  )
```


```{r include = FALSE}
# Keep important columns
```
```{r 12-keep-important-columns}
dict_data <-
  dict %>%
  mutate(
    data = map(weather_filename, ~ readxl::read_excel(here(.)))
  ) %>%
  select(-weather_filename)
dict_data
```
