```{r 35-remove-all, include = FALSE}
rm(list = ls())
```


## Multiple arguments

```{r include = FALSE}
### Multiple arguments

```
```{r 35-setup-35-function-details-r}
library(tidyverse)
library(here)


weather_path <- function(filename) {
  # Returned value
  here("data/weather", filename)
}
read_weather_file <- function(filename) {
  readxl::read_excel(weather_path(filename))
}
```


Multiple function arguments:

```{r include = FALSE}
# Multiple function arguments are separated by comma:
```
```{r 35-multiple-function-arguments-are-separated-by-comma}
read_weather_data <- function(omit_zurich = FALSE, omit_toronto = FALSE) {
  # Create ensemble dataset from files on disk
  weather_data <- bind_rows(
    berlin = read_weather_file("berlin.xlsx"),
    toronto = read_weather_file("toronto.xlsx"),
    tel_aviv = read_weather_file("tel_aviv.xlsx"),
    zurich = read_weather_file("zurich.xlsx"),
    .id = "city_code"
  )

  # Return it (filtered)
  weather_data %>%
    filter( !(city_code == "zurich" & omit_zurich) ) %>%
    filter( !(city_code == "toronto" & omit_toronto) )
}
```

Ellipsis (`...`) for list of arguments of unspecified length. Useful for passing arguments downstream:

```{r include = FALSE}
# Ellipsis: variable argument list, useful for passing arguments downstream
```
```{r 35-ellipsis-variable-argument-list-useful-for-passing-arguments-downstream}
weather_path <- function(...) {
  # All arguments are passed on
  here("data/weather", ...)
}

weather_path("berlin.xlsx")

weather_path("some", "subdir", "with", "a", "file.csv")
```


Mind, that despite altering the original function and adding new features to it, the original call still works as before:

```{r include = FALSE}
# Note: despite many changes and new features,
# the original call still works!
# (This can be tested automatically!)
```
```{r 35-note-despite-many-changes-and-new-features}
read_weather_data()
```


### Exercise

```{r include = FALSE}
## What does the following return? Why?
```
```{r 35-what-does-the-following-return-why}
read_weather_data(TRUE, omit_z = FALSE) %>%
  count(city_code)
```


See the next section for ideas on avoiding this behavior.
