```{r 42-remove-all, include = FALSE}
rm(list = ls())
```


## Closures

<!-- Setup 42-closure.R -->
```{r 42-setup-42-closure-r}
library(tidyverse)
library(here)

weather_path <- function(filename) {
  # Returned value
  here("data/weather", filename)
}
read_weather_file <- function(filename) {
  readxl::read_excel(weather_path(filename))
}
```

Closures can e.g. be used for the creation of functions. 
Here we create a function that loads a particular dataset:

<!-- Create a function that loads a particular dataset -->
```{r 42-create-a-function-that-loads-a-particular-dataset}
make_read_weather_file <- function(filename) {
  # Avoid odd effects due to lazy evaluation
  force(filename)

  # This function (closure) accesses the filename from the
  # outer function
  function() {
    read_weather_file(filename)
  }
}

read_berlin <- make_read_weather_file("berlin.xlsx")
read_toronto <- make_read_weather_file("toronto.xlsx")
read_tel_aviv <- make_read_weather_file("tel_aviv.xlsx")
read_zurich <- make_read_weather_file("zurich.xlsx")

read_berlin
read_berlin()
```

Use closures as wrappers for other verbs/functions (such functions are also called "adverbs"):

<!-- Use case: adverbs -- wrappers for other verbs -->
```{r 42-use-case-adverbs-wrappers-for-other-verbs}
loudly <- function(f) {
  force(f)

  function(...) {
    args <- list(...)
    msg <- paste0(length(args), " argument(s)")
    message(msg)

    f(...)
  }
}

read_loudly <- loudly(read_weather_file)
read_loudly
read_loudly("berlin.xlsx")
```
