```{r 72-remove-all, include = FALSE}
rm(list = ls())
```


## Iterating and traversing

<details><summary>Setup code</summary>
```{r include = FALSE}
### Iterating and traversing

```
```{r 72-setup-72-komoot-r}
library(tidyverse)
library(here)
```
</details>


```{r include = FALSE}
# Results from downloading geolocation data for all cities from photon.komoot.de:
```
```{r 72-results-from-downloading-geolocation-data-for-all-cities-from-photon-komoot-de}
komoot <- readRDS(here("data/komoot.rds"))

komoot
```


```{r include = FALSE}
# Results are stored in the "content" column:
```
```{r 72-results-are-stored-in-the-content-column}
komoot_content <-
  komoot %>%
  pull(content)

berlin <-
  komoot_content %>%
  pluck(1)

berlin %>%
  pluck("features", 1, "geometry", "coordinates")

toronto <-
  komoot_content %>%
  pluck(2)

toronto %>%
  pluck("features", 1, "geometry", "coordinates")
```


```{r include = FALSE}
# Apply same pluck() on all values with map():
```
```{r 72-apply-same-pluck-on-all-values-with-map}
komoot_content %>%
  map(~ pluck(., "features", 1, "geometry", "coordinates"))
```


```{r include = FALSE}
# Shortcut:
```
```{r 72-shortcut}
komoot_content %>%
  map(list("features", 1, "geometry", "coordinates"))

accessor <- list("features", 1, "geometry", "coordinates")
coordinates <-
  komoot_content %>%
  map(accessor)
coordinates
```
