```{r 73-remove-all, include = FALSE}
rm(list = ls())
```


## Iterating and traversing

<details><summary>Click here to make setup code visible</summary>
```{r include = FALSE}
### Iterating and traversing

```
```{r 73-setup-73-multi-r}
library(tidyverse)
library(here)

komoot <- readRDS(here("data/komoot.rds"))
komoot_content <-
  komoot %>%
  pull(content)
```
</details>


```{r include = FALSE}
# Use multiple accessors:
```
```{r 73-use-multiple-accessors}
accessor_coords <- list("features", 1, "geometry", "coordinates")
accessor_country <- list("features", 1, "properties", "country")

komoot_content %>%
  map(accessor_coords)

komoot_content %>%
  map(accessor_country)
```


```{r include = FALSE}
# All at once:
```
```{r 73-all-at-once}
accessors <- list(coords = accessor_coords, country = accessor_country)

accessors %>%
  map(~ map(komoot_content, .))

komoot_content %>%
  map(accessors)

coordinates


komoot_content <-
  komoot %>%
  pull(content)

berlin <-
  komoot_content %>%
  pluck(1)

berlin %>%
  pluck("features", 1, "geometry", "coordinates")

toronto <-
  komoot_content %>%
  pluck(2)

toronto %>%
  pluck("features", 1, "geometry", "coordinates")
```


```{r include = FALSE}
# Apply same pluck() on all values with map():
```
```{r 73-apply-same-pluck-on-all-values-with-map}
komoot_content %>%
  map(~ pluck(., "features", 1, "geometry", "coordinates"))
```


```{r include = FALSE}
# Shortcut:
```
```{r 73-shortcut}
komoot_content %>%
  map(list("features", 1, "geometry", "coordinates"))

accessor <- list("features", 1, "geometry", "coordinates")
coordinates <-
  komoot_content %>%
  map(accessor)
coordinates
```
