```{r 76-remove-all, include = FALSE}
rm(list = ls())
```


## Rectangling

<details><summary>Click here to make setup code visible</summary>
```{r include = FALSE}
### Rectangling

```
```{r 76-setup-75-rectangulate-r}
library(tidyverse)
library(here)

komoot <- readRDS(here("data/komoot.rds"))

komoot_content <-
  komoot %>%
  pull(content)

coordinates_transposed <-
  komoot_content %>%
  map(list("features", 1, "geometry", "coordinates")) %>%
  transpose() %>%
  map(~ flatten_dbl(.))
```
</details>


```{r include = FALSE}
# A tibble is internally a list of named vectors of equal length:
```
```{r 76-a-tibble-is-internally-a-list-of-named-vectors-of-equal-length}
coordinates_transposed %>%
  set_names(c("lon", "lat"))

coordinates_transposed %>%
  set_names(c("lon", "lat")) %>%
  as_tibble()
```


```{r include = FALSE}
# Name repair helps if you don't know the names yet
```
```{r 76-name-repair-helps-if-you-don-t-know-the-names-yet}
coordinates_transposed %>%
  as_tibble(.name_repair = "universal")

coordinates_transposed %>%
  as_tibble(.name_repair = "universal") %>%
  rename(lon = ...1, lat = ...2)
```
