```{r 91-remove-all, include = FALSE}
rm(list = ls())
```


## Dealing with state

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Dealing with state

```
```{r 91-setup-91-state-r}
library(tidyverse)
```
</details>


```{r include = FALSE}
# Write our own implementation of sum():
```
```{r 91-write-our-own-implementation-of-sum}
1 + 2 + 3
`+`(1, 2)
`+`(`+`(1, 2), 3)
```


```{r include = FALSE}
# Generalization: reduce()
```
```{r 91-generalization-reduce}
reduce(1:3, `+`)
reduce(1:3, ~ ..1 + ..2)
```


```{r include = FALSE}
# Initialization is implicit, but can be provided explicitly:
```
```{r 91-initialization-is-implicit-but-can-be-provided-explicitly}
reduce(1:3, `+`, .init = 0)
```


```{r include = FALSE}
# Operation does not need to commute or be associative,
# can be used to update state
```
```{r 91-operation-does-not-need-to-commute-or-be-associative}
diag(2)
reduce(1:3, `*`, .init = diag(2))
```


```{r include = FALSE}
# Write our own implementation of cumsum():
```
```{r 91-write-our-own-implementation-of-cumsum}
accumulate(1:3, `+`)
```
